### ISSUE TITLE
0 Call to a member function addStyleSheet() on null

### ISSUE THREAD

**Issue by AlainRnet** [zero-24/plg_system_customcss#1]
Hi.
After activating your plugin and renamed user.css to custom.css, all my administrator pages display "0 Call to a member function addStyleSheet() on null". I had to disable your plugin with phpmyadmin to recover plain access to the admin pages.

I try to activate your plugin after changing the name of custom.css and I don't have the error.
The problem appears when the css filename is custom.css or custom.min.css in css foler of isis admin template :-(
Even if the file is empty, the problem appears.

I hope this will helpfull, sorry for my bad english et thank you in advance for your help.
Best regards.

**Comment by AlainRnet** [comment]
Here are log informations :
 Exception Type: Error
File: /home/xxxxxxxxxx/web/plugins/system/customcss/customcss.php
Line: 50
Message: Call to a member function addStyleSheet() on null

#0 /home/xxxxxxxxxx/web/libraries/joomla/event/event.php(70): plgSystemcustomcss->onBeforeCompileHead()
#1 /home/xxxxxxxxxx/web/libraries/joomla/event/dispatcher.php(160): JEvent->update(Array)
#2 /home/xxxxxxxxxx/web/libraries/src/Application/BaseApplication.php(108): JEventDispatcher->trigger('onbeforecompile...', Array)
#3 /home/xxxxxxxxxx/web/libraries/src/Document/Renderer/Html/HeadRenderer.php(67): Joomla\CMS\Application\BaseApplication->triggerEvent('onBeforeCompile...')
#4 /home/xxxxxxxxxx/web/libraries/src/Document/Renderer/Html/HeadRenderer.php(38): Joomla\CMS\Document\Renderer\Html\HeadRenderer->fetchHead(Object(Joomla\CMS\Document\HtmlDocument))
#5 /home/xxxxxxxxxx/web/libraries/src/Document/HtmlDocument.php(501): Joomla\CMS\Document\Renderer\Html\HeadRenderer->render(NULL, Array, NULL)
#6 /home/xxxxxxxxxx/web/libraries/src/Document/HtmlDocument.php(793): Joomla\CMS\Document\HtmlDocument->getBuffer('head', NULL, Array)
#7 /home/xxxxxxxxxx/web/libraries/src/Document/HtmlDocument.php(567): Joomla\CMS\Document\HtmlDocument->_renderTemplate()
#8 /home/xxxxxxxxxx/web/libraries/src/Application/CMSApplication.php(1044): Joomla\CMS\Document\HtmlDocument->render(false, Array)
#9 /home/xxxxxxxxxx/web/libraries/src/Application/AdministratorApplication.php(450): Joomla\CMS\Application\CMSApplication->render()
#10 /home/xxxxxxxxxx/web/libraries/src/Application/CMSApplication.php(202): Joomla\CMS\Application\AdministratorApplication->render()
#11 /home/xxxxxxxxxx/web/administrator/index.php(51): Joomla\CMS\Application\CMSApplication->execute()
#12 {main}

If needed, I can have more informations from Akeeba admin tools, but I need to anonymize, so tell me back please.

**Comment by zero-24** [comment]
Thanks for your report @AlainRnet an update has been released here: https://github.com/zero-24/plg_system_customcss/releases/tag/3-5 seems I have cleaned up to much back then :D

**Comment by AlainRnet** [comment]
Many thanks. It works fine!
Best regards.
