### ISSUE TITLE
No more working for administrator template

### ISSUE THREAD

**Issue by AlainRnet** [zero-24/plg_system_customcss#4]
It no longer works in the administration because with each update, Joomla! moves custom.css in/media/templates/administrator/atum/css.

### Step to reproduce 
1. create custom.css
2. update et re-update Joomla!
3. you can see that custom.css has been moved to media/templates/administrator/atum/css

**Comment by zero-24** [comment]
Thanks for reporting and sorry for the late reply. This is interesting will apply another check for the new location in an upcomming version. Hopefully I do get the release out in the comming days.

**Comment by zero-24** [comment]
The issue has been fixed here and the release has been published: https://github.com/zero-24/plg_system_customcss/releases/tag/3-8

Thanks for your report :)
